option('distro_install',
  type : 'boolean',
  value : true,
  description : '安装共享库、头文件和 pkg-config 条目'
)
option('with_INIReader',
  type : 'boolean',
  value : true,
  description : '编译并在选择时安装 INIReader'
)
option('multi-line_entries',
  type : 'boolean',
  value : true,
  description : '按 Python ConfigParser 风格支持多行条目'
)
option('utf-8_bom',
  type : 'boolean',
  value : true,
  description : '允许 INI 文件开头出现 UTF-8 BOM 序列（0xEF 0xBB 0xBF）'
)
option('inline_comments',
  type : 'boolean',
  value : true,
  description : '允许使用注释前缀字符的行内注释'
)
option('inline_comment_prefix',
  type : 'string',
  value : ';',
  description : '行内注释的起始字符（启用时有效）'
)
option('start-of-line_comment_prefix',
  type : 'string',
  value : ';#',
  description : '行首注释的起始字符'
)
option('allow_no_value',
  type : 'boolean',
  value : false,
  description : '允许没有值的 name'
)
option('stop_on_first_error',
  type : 'boolean',
  value : false,
  description : '发生错误后停止解析'
)
option('report_line_numbers',
  type : 'boolean',
  value : false,
  description : '在 ini_handler 回调中报告行号'
)
option('call_handler_on_new_section',
  type : 'boolean',
  value : false,
  description : '每次遇到新 section 时调用 handler'
)
option('use_heap',
  type : 'boolean',
  value : false,
  description : '使用 malloc 在堆上分配内存，而不是使用栈上的固定大小行缓冲区'
)
option('max_line_length',
  type : 'integer',
  value : 200,
  description : '最大行长度（字节）'
)
option('initial_malloc_size',
  type : 'integer',
  value : 200,
  description : 'malloc 初始大小（字节，使用堆时有效）'
)
option('allow_realloc',
  type : 'boolean',
  value : false,
  description : '允许 malloc 初始大小增长到最大行长度（使用堆时有效）'
)
option('tests',
  type : 'boolean',
  value : true,
  description : '构建测试套件（输出较多）'
)
